# 07 Sep 2013 : PSW : New
# 25 Sep 2013 : PSW : Added admin 
# 26 Sep 2013 : PSW : Added tool, save, reload, print, bedbreak

name: BedCheck
main: com.yahoo.phil_work.bedcheck.BedCheck
version: 0.6
authors: [filber66]
description: BedCheck that tells you who has their spawn bed where you click

commands:
  bc:
    alias: bedcheck
    description: Admin BedCheck command prefix
    usage: <command> list|(tp <username>)|(tool [[bed]check|teleport <material>])|(rule [mustbe]own|[noone]else true|false)|save|reload|print
    permission: bedcheck.admin

permissions:
  bedcheck.admin:
    description: Allows listing and teleporting to other user's beds
    default: op
  bedcheck.own:
    description: Allows user to check their own bed
    default: true
  bedcheck.all:
    description: Allows user to check any bed
    default: op
  bedcheck.teleport:
    description: Allows teleport to home bed when clicking on a bed with defined tool
    default: op
  bedbreak.beds: 
    description: Overrides breakrule.mustbeown=true
    default: op
  bedbreak.others:
    description: Allows user to break someone else's bed. Only effective when breakrule.nooneelse true
    default: op
  bedcheck.*:
    children:
      bedcheck.all: true
      bedcheck.own: true
      bedcheck.teleport: true
      bedcheck.admin: true
  bedbreak.*:
    children:
      break.beds: true
      break.others: true
